# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88efe58a7e3a0364007a2d28975703efef27ab259a51e4244e20989dc26f76e0876066d0d851ab108b1b83ecf2d8f5541b009de4166f5efd39679999c7aa12a7

test:
  secret_key_base: e799942d72ad47366d6e66f8ff15760f0d0e5af7cefe1105868488ecfface0cae96daf78664e5f011fe203f7ee7d022e0a1efeaab112cca3b884f367645bca7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
